### ISSUE TITLE
Add a CRA Template for this project

### ISSUE THREAD

**Issue by LuisValgoi** [LuisValgoi/ui5-webcomponents-react-seed#23]
Create a CRA Template
e.g.: `ui5-webcomponents-react-ibso-seed`

**Comment by MarcusNotheis** [comment]
I would recommend looking into [cra templates](https://create-react-app.dev/docs/custom-templates), e.g.[ ui5-webcomponents-react](https://github.com/SAP/ui5-webcomponents-react/tree/master/packages/cra-template)

**Comment by LuisValgoi** [comment]
niceeeee @MarcusNotheis 
it fits perfectly!!!
thank you for that
