### ISSUE TITLE
[FEATURE] Add prettier

### ISSUE THREAD

**Issue by marceloschreiber** [LuisValgoi/ui5-webcomponents-react-seed#25]
**Describe your suggestion**
Add prettier to dev dependency.

**Additional context**
It's pretty standard on React to have prettier integrated with VSCode in order to have an organized codebase.

**Comment by LuisValgoi** [comment]
Hey @marceloschreiber 

Thank you or the suggestion.

Regarding this topic, Do you have any example on a prettierconfig file?

We have used one on this project [here](https://github.wdf.sap.corp/CloudSCAME/WEConnect-Frontend/) and we didn't like the result of that.

It would be very helpful to get a better example.
