### ISSUE TITLE
[FEATURE] Add react-helmet

### ISSUE THREAD

**Issue by marceloschreiber** [LuisValgoi/ui5-webcomponents-react-seed#26]
**Describe your suggestion**
Add `react-helmet` to help create applications where each page has a title that reflects the content of that page. If we think in terms of UX it's important that the title reflects the route the user is, yet this detail is often forgotten.

**Additional context**
Without using something like `react-helmet` the title and metatags will be the same for all routes as defined on `public/index.html`.

**Comment by LuisValgoi** [comment]
Really thank you for that!
A very good catch!
We will handle it in the next days!

**Comment by LuisValgoi** [comment]
https://github.com/nfl/react-helmet

**Comment by LuisValgoi** [comment]
https://medium.com/collabcode/como-manipular-o-head-das-p%C3%A1ginas-react-utilizando-o-react-helmet-da-nfl-c10481a74782
