### ISSUE TITLE
Use CSS Variables for styling

### ISSUE THREAD

**Issue by isaqueha** [LuisValgoi/ui5-webcomponents-react-seed#48]
We should use CSS variables like var(--sapWarningColor).
Refactor the use of colors, sizes, and other common values around the application.
Example

```
style={{
    width: '1.5rem',
    height: '1.5rem',
    color: 'var(--sapWarningColor)'
})

{
--sapWarningColor: #feb60a;
}
```

**Comment by isaqueha** [comment]
Is this done? We don't need it anymore?

**Comment by LuisValgoi** [comment]
Yeah, its done
