### ISSUE TITLE
Refactor Constants to the Component level

### ISSUE THREAD

**Issue by isaqueha** [LuisValgoi/ui5-webcomponents-react-seed#49]
We should move Constants used in each component to the file it is being used, so it's on the same level. This way each variable will be on its context.
Example of change for the `useRequest` hook:

```
REQUEST: {
    GET: 'get',
    POST: 'get',
    PUT: 'put',
    PATCH: 'patch',
    DELETE: 'delete',
}
```

For constants that are being used by multiple components, we can keep them all in the  `Constants.js` file.

**Comment by isaqueha** [comment]
Is this done? We don't need it anymore?

**Comment by LuisValgoi** [comment]
@isaqueha its done!
https://github.com/LuisValgoi/ui5-webcomponents-react-seed/commit/d546e9cb05c1ff1ad1d49b65f3ed4267cdd1395f
and here
https://github.com/LuisValgoi/ui5-webcomponents-react-seed/commit/50042fb6c72e4ed1728457881862935a087b01e4
