### ISSUE TITLE
[ISSUE] Generated Project Default README

### ISSUE THREAD

**Issue by rafaelferrari** [LuisValgoi/ui5-webcomponents-react-seed#69]
**Describe the issue**
- When generating a project using the seed as a template, I get the image and the stats from this repository cloned to my own in the `README.md` file

![image](https://user-images.githubusercontent.com/4932892/95108743-0d5df800-0712-11eb-9c2c-1dc142b5dabc.png)

**Expected behavior**
- I'd expect it to generate a clean readme containing the commands, maybe you can add in the bottom something like "generated using UI5 WebComponents React Seed" with a link to this, but the way it currently is I'll certainly just remove it from the README file

**Comment by LuisValgoi** [comment]
It can be also related to #53

**Comment by LuisValgoi** [comment]
I have fixed it on the npm version 1.4.0
